// import { StandardButton , LineEdit} from "std-widgets.slint";
import {SURDialog, SURButton, SURInput} from "../../SurrealismUI-main/index.slint";
// import { Button } from "../../SurrealismUI-main/src/button/button.slint";

export struct LoginInfos {
    name:string,
    password:string,
}
export global Lgo {
    callback login_clicked(LoginInfos);
    callback login_cancel;
}
export component Login inherits Rectangle {
        VerticalLayout {
          padding: 20px;
          alignment: center;
          spacing: 10px;
            HorizontalLayout{
              padding: 50px;
              alignment:center;
              spacing: 30px;
                Text {text : @tr("账号：");
                font-size: 14px;
                font-weight: 650;}
                name_input := SURInput { 
                  width: 40%;
                    placeholder : @tr("输入账号....");
                    font-size : 14px;
                    clearable: true;
                 }
            }
            HorizontalLayout{
              padding: 20px;
              alignment: center;
              spacing: 30px;
                Text {text : @tr("密码：");
                font-size: 14px;
                font-weight: 650;}
                password_input := SURInput { 
                  width: 40%;
                    placeholder : @tr("输入密码....");
                    font-size: 14px;
                    type:InputType.password;
                    password: true;
                    clearable: true;
                }
            }
            HorizontalLayout {
              padding: 50px;
              alignment: center;
              spacing: 100px;
              SURButton { 
                  width: 70px;
                  height: 32px;
                  text: "取消";
                  clicked => {
                    Lgo.login-cancel()
                  }
               }
               SURButton {
                width: 70px;
                  height: 32px;
                  text: "登录";
                  clicked => {
                    Lgo.login_clicked({
                      name:name_input.get(),
                      password:password-input.get(),
                    })
                  }
               }
            }
           
        }

    
  }