import { StyleMetrics } from "std-widgets.slint";
import { MenuBar} from "menubar.slint";
import { Login, LoginInfos,Lgo} from "pages/login.slint";
import { QueryPage,Action,Infos_Box,Infos_Sn,InfosData,DateTimeAdapter,Dia,QueryTime} from "pages/query.slint";
export { QueryPage,Action,Infos_Box,Infos_Sn,InfosData,DateTimeAdapter,Dia,QueryTime,Login,LoginInfos,Lgo}

export component App inherits Window {
    width: 1600px;
    height: 800px;
    icon: @image-url("../resources/logo/logo.png");
    callback login_clicked <=> Lgo.login_clicked;
    callback login_cancel <=> Lgo.login_cancel;
    callback show_confirm_popup <=> dia.show_confirm_popup;
    in-out property <bool> is-login :true ;
    background: StyleMetrics.window-background;
    title: @tr("Slint_Tools");
    
    if root.is-login == false : Login {}
    if root.is-login == true : HorizontalLayout {
        menu := MenuBar {}
        if(menu.active == 0) :  QueryPage { }
    }
    dia := Dia { }
    
}
